# Generated by Django 4.2.4 on 2023-12-04 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
